twig:
    default_path: '%kernel.project_dir%/templates'
    form_themes:
        - bootstrap_4_layout.html.twig
#Partie 79 : Twig: injecter une variable globale dans les templates
    globals:
        categoryRepository: "@App\\Repository\\CategoryRepository"